var eRed = instance_create_depth(17, 20, -1, oButton); // 64x64
eRed.text = "";
eRed._width = 24;
eRed._height = 24;
eRed.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eRed.func = function () { instance_create_depth(x,y,-1,oEnemyRed); };
eRed.image = sEnemyRed;
var eBlue = instance_create_depth(47, 20, -1, oButton); // 64x64
eBlue.text = "";
eBlue._width = 24;
eBlue._height = 24;
eBlue.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eBlue.func = function () { instance_create_depth(x,y,-1,oEnemyBlue); };
eBlue.image = sEnemyBlue;
var eGreen = instance_create_depth(17, 50, -1, oButton); // 64x64
eGreen.text = "";
eGreen._width = 24;
eGreen._height = 24;
eGreen.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eGreen.func = function () { instance_create_depth(x,y,-1,oEnemyGreen); };
eGreen.image = sEnemyGreen;
var eYellow = instance_create_depth(47, 50, -1, oButton); // 64x64
eYellow.text = "";
eYellow._width = 24;
eYellow._height = 24;
eYellow.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eYellow.func = function () { instance_create_depth(x,y,-1,oEnemyYellow); };
eYellow.image = sEnemyYellow;
var ePink = instance_create_depth(17, 80, -1, oButton); // 64x64
ePink.text = "";
ePink._width = 24;
ePink._height = 24;
ePink.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
ePink.func = function () { instance_create_depth(x,y,-1,oEnemyPink); };
ePink.image = sEnemyPink;
var eBlack = instance_create_depth(47, 80, -1, oButton); // 64x64
eBlack.text = "";
eBlack._width = 24;
eBlack._height = 24;
eBlack.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eBlack.func = function () { instance_create_depth(x,y,-1,oEnemyBlack); };
eBlack.image = sEnemyBlack;
var eWhite = instance_create_depth(17, 110, -1, oButton); // 64x64
eWhite.text = "";
eWhite._width = 24;
eWhite._height = 24;
eWhite.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eWhite.func = function () { instance_create_depth(x,y,-1,oEnemyWhite); };
eWhite.image = sEnemyWhite;
var eZebra = instance_create_depth(47, 110, -1, oButton); // 64x64
eZebra.text = "";
eZebra._width = 24;
eZebra._height = 24;
eZebra.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eZebra.func = function () { instance_create_depth(x,y,-1,oEnemyZebra); };
eZebra.image = sEnemyZebra;
var eRainbow = instance_create_depth(17, 140, -1, oButton); // 64x64
eRainbow.text = "";
eRainbow._width = 24;
eRainbow._height = 24;
eRainbow.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eRainbow.func = function () { instance_create_depth(x,y,-1,oEnemyRainbow); };
eRainbow.image = sEnemyRainbow;
var eCeramic = instance_create_depth(47, 140, -1, oButton); // 64x64
eCeramic.text = "";
eCeramic._width = 24;
eCeramic._height = 24;
eCeramic.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eCeramic.func = function () { instance_create_depth(x,y,-1,oEnemyCeramic); };
eCeramic.image = sEnemyCeramic;
var eBoss = instance_create_depth(17, 170, -1, oButton); // 64x64
eBoss.text = "";
eBoss._width = 24;
eBoss._height = 24;
eBoss.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eBoss.func = function () { instance_create_depth(x,y,-1,oEnemyBoss); };
eBoss.image = sEnemyBoss;
var eTestEnemy = instance_create_depth(47, 170, -1, oButton); // 64x64
eTestEnemy.text = "";
eTestEnemy._width = 24;
eTestEnemy._height = 24;
eTestEnemy.colors = {main: c_black, outline:c_white, hover:c_aqua, bgcolor:c_white, text:c_white};
eTestEnemy.func = function () { instance_create_depth(x,y,-1,oEnemyTestEnemy); };
eTestEnemy.image = sEnemyTestEnemy;






var destroyAllEnemiesButton = instance_create_depth(16, 461, -1, oButton);
destroyAllEnemiesButton.text = "X";
destroyAllEnemiesButton._width = 32;
destroyAllEnemiesButton._height = 32;
destroyAllEnemiesButton.colors = {main: c_aqua, outline:c_white, hover:c_orange, bgcolor:c_white, text:c_black};
destroyAllEnemiesButton.func = function () { instance_destroy(oEnemy); };


var homeButton = instance_create_depth(591, 461, -1, oButton);
homeButton.text = "Home";
homeButton._width = 96;
homeButton._height = 32;
homeButton.colors = {main: c_aqua, outline:c_white, hover:c_orange, bgcolor:c_white, text:c_black};
homeButton.func = function () { room_goto(RoomStart); };